let questions = [
    {
        "question": "Wer hat HTML erfunden?",
        "answer_1": "Robbie Williams",
        "answer_2": "Albert Einstein",
        "answer_3": "Tim Berners-Lee",
        "answer_4": "Nikolar Tesla",
        "right_answer": 3,
    },
    {
        "question": "Welches Attribut kann man NICHT für Textarea verwenden?",
        "answer_1": "readonly",
        "answer_2": "max",
        "answer_3": "from",
        "answer_4": "spellcheck",
        "right_answer": 1,
    },
    {
        "question": "Wie hieß einer der ersten Homecomputer?",
        "answer_1": "D64-a",
        "answer_2": "ATA Lerchon",
        "answer_3": "ZX Spectrum",
        "answer_4": "Lightning Sven",
        "right_answer": 3,
    },
    {
        "question": "Welches ist das älteste Textverarbeitungsprogramm?",
        "answer_1": "Word 1.25",
        "answer_2": "ABC Texter",
        "answer_3": "Textmaster",
        "answer_4": "Wordstar",
        "right_answer": 4,
    },
    {
        "question": "Welchen Prozesser nutzte der erste IBM-PC Modell 5150?",
        "answer_1": "8088",
        "answer_2": "JC 51",
        "answer_3": "88-5150",
        "answer_4": "Intel One",
        "right_answer": 1,
    },
    {
        "question": "Mit welcher Programmiersprache arbeiteten die ersten Homecomputer?",
        "answer_1": "Pascal",
        "answer_2": "CC",
        "answer_3": "COBOL",
        "answer_4": "Basic",
        "right_answer": 4,
    },
];